// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcF0WbJPWL8dL3Koc3SrvnT_0waRSh1YE',
    appId: '1:928231388347:web:0840fdf5f4dffc7b59259e',
    messagingSenderId: '928231388347',
    projectId: 'chat-application-flutter-d8092',
    authDomain: 'chat-application-flutter-d8092.firebaseapp.com',
    storageBucket: 'chat-application-flutter-d8092.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB21Kyg0YdkkMQPPA-NyQDItoZu-Z8rwCw',
    appId: '1:928231388347:android:e3ddda0e68f0ef6c59259e',
    messagingSenderId: '928231388347',
    projectId: 'chat-application-flutter-d8092',
    storageBucket: 'chat-application-flutter-d8092.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyFyKA8NBEd2nfK9KSDccM-LEGehFwdZU',
    appId: '1:928231388347:ios:adb0dcf37de6e40f59259e',
    messagingSenderId: '928231388347',
    projectId: 'chat-application-flutter-d8092',
    storageBucket: 'chat-application-flutter-d8092.appspot.com',
    iosBundleId: 'com.chatapplication.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyFyKA8NBEd2nfK9KSDccM-LEGehFwdZU',
    appId: '1:928231388347:ios:adb0dcf37de6e40f59259e',
    messagingSenderId: '928231388347',
    projectId: 'chat-application-flutter-d8092',
    storageBucket: 'chat-application-flutter-d8092.appspot.com',
    iosBundleId: 'com.chatapplication.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcF0WbJPWL8dL3Koc3SrvnT_0waRSh1YE',
    appId: '1:928231388347:web:115d05c2a79d3dbb59259e',
    messagingSenderId: '928231388347',
    projectId: 'chat-application-flutter-d8092',
    authDomain: 'chat-application-flutter-d8092.firebaseapp.com',
    storageBucket: 'chat-application-flutter-d8092.appspot.com',
  );
}